version: '3.1'
services:
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: food-delivery-api
    container_name: food-delivery-api
    ports:
      - '8080:8080'
      - '5005:5005'
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=dev
    links:
      - db
  db:
    image: mysql
    container_name: food-delivery-db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - data-volume:/var/lib/mysql
volumes: 
  data-volume:
