version: '3.1'
services:
  food-delivery-api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: food-delivery/api
    ports:
      - '8080:8080'
      - '5005:5005'
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=dev
    links:
      - db
  db:
    image: mysql
    container_name: food_delivery_api
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=food_delivery_api
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql
