version: '3.1'
services:
  db:
    image: mysql
    container_name: food_delivery_api
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - data-volume:/var/lib/mysql
volumes:
  data-volume: